/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Submission;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ishmam
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        setSize(720 , 480);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Cake1 = new javax.swing.JTextField();
        Cake = new javax.swing.JButton();
        Rice1 = new javax.swing.JTextField();
        Rice = new javax.swing.JButton();
        Beef1 = new javax.swing.JTextField();
        Beef = new javax.swing.JButton();
        Pudding = new javax.swing.JButton();
        Pudding1 = new javax.swing.JTextField();
        Vegetable1 = new javax.swing.JTextField();
        Vegetable = new javax.swing.JButton();
        Fish1 = new javax.swing.JTextField();
        FIsh = new javax.swing.JButton();
        Egg1 = new javax.swing.JTextField();
        Egg = new javax.swing.JButton();
        Khichuri1 = new javax.swing.JTextField();
        Khichuri = new javax.swing.JButton();
        Chicken1 = new javax.swing.JTextField();
        Chicken = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Egg.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(460, 0, 300, 230);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cake.jpg"))); // NOI18N
        jLabel12.setText("jLabel11");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 10, 300, 220);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Chicken.jpg"))); // NOI18N
        jLabel13.setText("jLabel11");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(920, 250, 300, 230);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fish.jpg"))); // NOI18N
        jLabel14.setText("jLabel11");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(460, 250, 300, 225);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Khichuri.jpg"))); // NOI18N
        jLabel15.setText("jLabel11");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(920, 0, 300, 230);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pudding.jpg"))); // NOI18N
        jLabel16.setText("jLabel11");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 500, 300, 220);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rice.jpg"))); // NOI18N
        jLabel17.setText("jLabel11");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(920, 500, 300, 220);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vegetable.jpg"))); // NOI18N
        jLabel18.setText("jLabel11");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(460, 500, 300, 225);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Beef.jpg"))); // NOI18N
        jLabel19.setText("jLabel11");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(10, 250, 300, 230);

        jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Rice");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1230, 560, 140, 40);

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Cake");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 90, 70, 40);

        jLabel3.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Beef");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 330, 70, 40);

        jLabel4.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Pudding");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 560, 120, 40);

        jLabel5.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Vegetable");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(770, 560, 140, 40);

        jLabel6.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("Fish");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(770, 330, 140, 40);

        jLabel7.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("Egg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(770, 80, 140, 40);

        jLabel8.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 51));
        jLabel8.setText("Khichuri");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1230, 80, 140, 50);

        jLabel9.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setText("Chicken");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1230, 320, 140, 40);
        getContentPane().add(Cake1);
        Cake1.setBounds(320, 130, 120, 40);

        Cake.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        Cake.setText("update");
        Cake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CakeActionPerformed(evt);
            }
        });
        getContentPane().add(Cake);
        Cake.setBounds(320, 180, 90, 40);
        getContentPane().add(Rice1);
        Rice1.setBounds(1230, 600, 120, 40);

        Rice.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        Rice.setText("update");
        Rice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiceActionPerformed(evt);
            }
        });
        getContentPane().add(Rice);
        Rice.setBounds(1230, 650, 90, 40);
        getContentPane().add(Beef1);
        Beef1.setBounds(320, 380, 120, 40);

        Beef.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        Beef.setText("update");
        Beef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeefActionPerformed(evt);
            }
        });
        getContentPane().add(Beef);
        Beef.setBounds(320, 430, 90, 40);

        Pudding.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        Pudding.setText("update");
        Pudding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuddingActionPerformed(evt);
            }
        });
        getContentPane().add(Pudding);
        Pudding.setBounds(320, 660, 90, 40);
        getContentPane().add(Pudding1);
        Pudding1.setBounds(320, 610, 120, 40);
        getContentPane().add(Vegetable1);
        Vegetable1.setBounds(770, 600, 120, 40);

        Vegetable.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        Vegetable.setText("update");
        Vegetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VegetableActionPerformed(evt);
            }
        });
        getContentPane().add(Vegetable);
        Vegetable.setBounds(770, 650, 90, 40);
        getContentPane().add(Fish1);
        Fish1.setBounds(770, 370, 120, 40);

        FIsh.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        FIsh.setText("update");
        FIsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIshActionPerformed(evt);
            }
        });
        getContentPane().add(FIsh);
        FIsh.setBounds(770, 420, 90, 40);

        Egg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Egg1ActionPerformed(evt);
            }
        });
        getContentPane().add(Egg1);
        Egg1.setBounds(770, 130, 120, 40);

        Egg.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        Egg.setText("update");
        Egg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EggActionPerformed(evt);
            }
        });
        getContentPane().add(Egg);
        Egg.setBounds(770, 180, 90, 40);
        getContentPane().add(Khichuri1);
        Khichuri1.setBounds(1230, 130, 120, 40);

        Khichuri.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        Khichuri.setText("update");
        Khichuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KhichuriActionPerformed(evt);
            }
        });
        getContentPane().add(Khichuri);
        Khichuri.setBounds(1230, 180, 90, 40);
        getContentPane().add(Chicken1);
        Chicken1.setBounds(1230, 360, 120, 40);

        Chicken.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        Chicken.setText("update");
        Chicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenActionPerformed(evt);
            }
        });
        getContentPane().add(Chicken);
        Chicken.setBounds(1230, 410, 90, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Texture.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-40, -100, 1790, 1060);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void CakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CakeActionPerformed
        // TODO add your handling code here:
        Cakeup = Cake1.getText().toString();
        JOptionPane.showMessageDialog(this,"Updated");
        Cake1.setText(null);             
    }//GEN-LAST:event_CakeActionPerformed

    private void RiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiceActionPerformed
        // TODO add your handling code here:
        Riceup = Rice1.getText().toString();
        JOptionPane.showMessageDialog(this,"Updated");
        Rice1.setText(null); 
    }//GEN-LAST:event_RiceActionPerformed

    private void BeefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeefActionPerformed
        // TODO add your handling code here:
        Beefup = Beef1.getText().toString();
        JOptionPane.showMessageDialog(this,"Updated");
        Beef1.setText(null);
    }//GEN-LAST:event_BeefActionPerformed

    private void PuddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuddingActionPerformed
        // TODO add your handling code here:
        Puddingup = Pudding1.getText().toString();
        JOptionPane.showMessageDialog(this,"Updated");
        Pudding1.setText(null);
    }//GEN-LAST:event_PuddingActionPerformed

    private void VegetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VegetableActionPerformed
        // TODO add your handling code here:
        Vegetableup = Vegetable1.getText().toString();
        JOptionPane.showMessageDialog(this,"Updated");
        Vegetable1.setText(null);
    }//GEN-LAST:event_VegetableActionPerformed

    private void FIshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIshActionPerformed
        // TODO add your handling code here;
        Fishup = Fish1.getText().toString();
        JOptionPane.showMessageDialog(this,"Updated");
        Fish1.setText(null);
    }//GEN-LAST:event_FIshActionPerformed

    private void Egg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Egg1ActionPerformed
    }//GEN-LAST:event_Egg1ActionPerformed

    private void EggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EggActionPerformed
        Eggup = Egg1.getText().toString();
        JOptionPane.showMessageDialog(this,"Updated");
        Egg1.setText(null);
    }//GEN-LAST:event_EggActionPerformed

    private void KhichuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KhichuriActionPerformed
        // TODO add your handling code here:
           Khichuriup = Khichuri1.getText().toString();
        JOptionPane.showMessageDialog(this,"Updated");
        Khichuri1.setText(null);
    }//GEN-LAST:event_KhichuriActionPerformed

    private void ChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenActionPerformed
        // TODO add your handling code here:
         Chickenup = Chicken1.getText().toString();
        JOptionPane.showMessageDialog(this,"Updated");
        Chicken1.setText(null);
    }//GEN-LAST:event_ChickenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Beef;
    private javax.swing.JTextField Beef1;
    private javax.swing.JButton Cake;
    private javax.swing.JTextField Cake1;
    private javax.swing.JButton Chicken;
    private javax.swing.JTextField Chicken1;
    private javax.swing.JButton Egg;
    private javax.swing.JTextField Egg1;
    private javax.swing.JButton FIsh;
    private javax.swing.JTextField Fish1;
    private javax.swing.JButton Khichuri;
    private javax.swing.JTextField Khichuri1;
    private javax.swing.JButton Pudding;
    private javax.swing.JTextField Pudding1;
    private javax.swing.JButton Rice;
    private javax.swing.JTextField Rice1;
    private javax.swing.JButton Vegetable;
    private javax.swing.JTextField Vegetable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
    public String Cakeup,Riceup,Beefup,Chickenup, Vegetableup, Eggup, Khichuriup, Fishup,Puddingup;
}
